var canvas=document.getElementById("myCanvas");
var ctx=canvas.getContext("2d");
var grd=ctx.createLinearGradient(0,0,200,0);
grd.addColorStop(0,"red");
grd.addColorStop(1,"black");
ctx.fillStyle=grd;
ctx.fillRect(10,10,150,80);
var canvas1=document.getElementById("myCanvas2");
var ctx=canvas1.getContext("2d");
var grd=ctx.createRadialGradient(75,50,5,90,60,100);
grd.addColorStop(0,"red");
grd.addColorStop(1,"black");
ctx.fillStyle=grd;
ctx.fillRect(10,10,150,80);
var canvas2=document.getElementById("myCanvas3");
var ctx=canvas2.getContext("2d");
ctx.font="30px Comic Sans MS";
ctx.fillStyle="red";
ctx.textAlign="center";
ctx.fillText("Hello World",canvas2.width/2,canvas2.height/2);
var canvas = document.getElementById("myCanvas4");
var ctx = canvas.getContext("2d");
ctx.font = "30px Arial";
ctx.strokeText("Hello World",10,50);
